{{- if and (eq .Values.sandbox "true") .Values.restore.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-restore-{{ .Values.deployEnv }}
  labels:
    deployEnv: {{ .Values.deployEnv | quote }}
    {{- include "sefaria.labels" . | nindent 4 }}
  annotations: 
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: hook-succeeded, hook-failed
    helm.sh/hook-weight: "5"
data: 
  restore-mongo.sh: |-  
    #!/bin/bash
    set -e
    set -x

    tar xzvf /storage/dump.tar.gz -C /storage 
    if [[ -z "$MONGO_HOST" ]]; then
      echo "Mongo Host not specified"
      exit 1
    fi

    # Cast json-string host list intended for local settings into a raw URI string
    # Since host can be a replicaset with multiple hosts/ports, this string should contain both
    if [[ $MONGO_HOST =~ "," ]]; then
      apt-get update && apt-get install curl
      curl -sLo jq https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
      chmod +x jq
      MONGO_HOST=$(echo $MONGO_HOST | ./jq -r '. | @tsv' - | sed 's/\t/,/g')
    fi

    URI="mongodb://"

    if [[ ! -z SEFARIA_DB_USER ]]; then
      URI="${URI}${SEFARIA_DB_USER}"
      if [[ ! -z SEFARIA_DB_PASSWORD ]]; then
          URI="${URI}:${SEFARIA_DB_PASSWORD}"
      fi
      URI="${URI}@"
    fi
    {{- if eq .Values.sandbox "true" }}
    SEFARIA_DB="${SEFARIA_DB}-{{ .Values.deployEnv | quote }}"
    {{- end }}

    URI="${URI}${MONGO_HOST}/?ssl=false&authSource=admin"

    if [[ ! -z "MONGO_REPLICASET" ]]; then
    URI="${URI}&replicaSet=${MONGO_REPLICASET}"
    fi

    mongorestore --drop --uri="$URI" -v -d "${SEFARIA_DB}" --dir=/storage/dump/sefaria
{{- end }}
