{{- if and (eq .Values.sandbox "true") .Values.restore.cleanup  }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: destroy-mongo-{{ .Values.deployEnv }}
  labels:
    deployEnv: {{ .Values.deployEnv | quote }}
    {{- include "sefaria.labels" . | nindent 4 }}
  annotations: 
    helm.sh/hook: post-delete
    helm.sh/hook-delete-policy: hook-succeeded
    helm.sh/hook-weight: "5"
data: 
  destroy-mongo.sh: |-  
    #!/bin/bash
    set -e
    set -x

    if [[ -z "$MONGO_HOST" ]]; then
      echo "Mongo Host not specified"
      exit 1
    fi

    URI="mongodb://"

    if [[ ! -z SEFARIA_DB_USER ]]; then
      URI="${URI}${SEFARIA_DB_USER}"
      if [[ ! -z SEFARIA_DB_PASSWORD ]]; then
          URI="${URI}:${SEFARIA_DB_PASSWORD}"
      fi
      URI="${URI}@"
    fi

    URI="${URI}${MONGO_HOST}/?ssl=false&authSource=admin"

    if [[ ! -z "MONGO_REPLICASET_NAME" ]]; then
    URI="${URI}&replicaSet=${MONGO_REPLICASET_NAME}"
    fi

    {{- if eq .Values.sandbox "true" }}
    DATABASE="${SEFARIA_DB}-{{ .Values.deployEnv | quote }}"
    {{- else }}
    DATABASE="${SEFARIA_DB}"
    {{- end }}


    mongo --uri "$URI" $DATABASE <<EOF
    db.dropDatabase();
    EOF
    
    mongo --uri "$URI" apscheduler-{{ .Values.deployEnv }} <<EOF
    db.dropDatabase();
    EOF
{{- end }}
