# Depends on varnish operator being installed: https://ibm.github.io/varnish-operator/
# Mutually exclusive with the varnish rollout - use that if the varnish controller is not installed
{{- if .Values.varnish.managed }}
apiVersion: caching.ibm.com/v1alpha1
kind: VarnishCluster
metadata:
  labels:
    operator: varnish
  name: {{ .Values.deployEnv }}-varnish
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - mongo
        topologyKey: kubernetes.io.hostname
    nodeAffinity:
      {{- include "sefaria.nodeAffinities" $ | nindent 6 }}
  backend:
    selector:
      app: "web-{{ Values.deployEnv }}"
    port: 80 
  monitoring:
    {{- toYaml $.Values.varnish.monitoring | nindent 4 }}
  replicas: {{ $.Values.varnish.replicaCount }}
  service:
    port: 8040
    type: ClusterIP
  varnish:
    admAuth:
      secretName: {{ template "sefaria.secrets.varnish" $ }} 
      key: varnish-secret
    args:
      - "-s"
      - "malloc,{{ Values.varnish.tuning.malloc }}"
      - "-p"
      - "nuke_limit={{ Values.varnish.tuning.nuke_limit }}"
      - "-p"
      - "thread_pool_max={{ Values.varnish.tuning.thread_pool_max }}"
      - "-p"
      - "first_byte_timeout={{ Values.varnish.tuning.first_byte_timeout }}"
      - "-p"
      - "between_bytes_timeout={{ Values.varnish.tuning.between_bytes_timeout }}" 
    resources: {{ toYaml Values.varnish.resources | nindent 6 }}
  vcl:
    configMapName: {{ Values.deployEnv }}-varnish-vcl
    entrypointFileName: sefaria.vcl
{{- end }}
